"use client";

import { useEffect, useMemo, useState } from "react";
import RequireAuth from "@/components/RequireAuth";
import AppShell from "@/components/AppShell";
import StatCard from "@/components/StatCard";
import { adminApi } from "@/lib/api";

function LearningAdmin(){const[overview,setOverview]=useState(null),[users,setUsers]=useState([]),[activity,setActivity]=useState([]),[search,setSearch]=useState(""),[page,setPage]=useState(1),[pages,setPages]=useState(1),[selected,setSelected]=useState(null),[detail,setDetail]=useState(null),[busy,setBusy]=useState(true);
 async function load(){setBusy(true);try{const[o,u,a]=await Promise.all([adminApi.overview(),adminApi.users({search,page,limit:20}),adminApi.activity(40)]);setOverview(o);setUsers(u.items||[]);setPages(u.pages||1);setActivity(a||[]);}finally{setBusy(false);}}
 useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t);},[search,page]);
 useEffect(()=>{if(!selected){setDetail(null);return;}adminApi.user(selected).then(setDetail).catch(()=>setDetail(null));},[selected]);
 const avg=useMemo(()=>{const arr=(detail?.tests||[]).filter(x=>x.total_marks).map(x=>x.score/x.total_marks*100);return arr.length?(arr.reduce((a,b)=>a+b,0)/arr.length).toFixed(1):"0.0";},[detail]);
 return <AppShell admin title="Junior insights" subtitle="AI, prediction, adaptive-test and tutor activity from the same MongoDB student accounts" actions={<button className="secondary-btn compact" onClick={()=>adminApi.downloadStudents()}>Export portfolio PDF</button>}>
  <section className="stats-grid six compact-stats"><StatCard label="Students" value={overview?.total_users??"—"}/><StatCard label="Active 24h" value={overview?.active_24h??"—"} tone="blue"/><StatCard label="Online" value={overview?.online_now??"—"} tone="success"/><StatCard label="High risk" value={overview?.high_risk??"—"} tone="danger"/><StatCard label="Tests 24h" value={overview?.tests_24h??"—"} tone="purple"/><StatCard label="Tutor queries 24h" value={overview?.chats_24h??"—"}/></section>
  <div className="dashboard-grid junior-admin-grid"><section className="panel-card"><div className="admin-list-header"><div><h2>Students</h2><p className="muted admin-section-note">Click a student to inspect Junior learning history.</p></div><input className="search-input admin-search" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Search student"/></div>{busy?<div className="empty-state compact-empty"><strong>Loading…</strong></div>:<div className="junior-admin-table"><div className="junior-admin-row header"><span>Student</span><span>Risk</span><span>Predicted</span><span>Tests</span><span>Average</span><span>Tutor</span></div>{users.map(u=><button key={u.id} className="junior-admin-row" onClick={()=>setSelected(u.id)}><span><strong>{u.name||u.profile?.name||"Student"}</strong><small>{u.email}</small></span><span><span className={`pill ${u.latest_progress?.risk_level==="High"?"danger":u.latest_progress?.risk_level==="Low"?"success":"warning"}`}>{u.latest_progress?.risk_level||"No data"}</span></span><span>{u.latest_progress?.total_predicted_marks??"—"}</span><span>{u.test_stats?.count||0}</span><span>{u.test_stats?.average_score||0}%</span><span>{u.chat_stats?.count||0}</span></button>)}</div>}<div className="admin-pagination"><button disabled={page<=1} onClick={()=>setPage(v=>v-1)}>Previous</button><span>{page} / {pages}</span><button disabled={page>=pages} onClick={()=>setPage(v=>v+1)}>Next</button></div></section>
  <section className="panel-card"><div className="section-heading"><h2>Recent activity</h2></div><div className="admin-activity-list">{activity.map(a=><div className="admin-activity-row" key={a.id}><div><strong>{a.user?.name||a.user?.email||"Student"}</strong><small>{String(a.action||"").replaceAll("_"," ")}{a.page?` · ${a.page}`:""}</small></div><small>{a.createdAt?new Date(a.createdAt).toLocaleString():"—"}</small></div>)}{!activity.length&&<div className="empty-state compact-empty"><strong>No activity yet</strong></div>}</div></section></div>
  {detail&&<section className="panel-card junior-detail-study"><div className="section-heading"><div><h2>{detail.user?.name||detail.user?.profile?.name||"Student"}</h2><p className="muted">{detail.user?.email}</p></div><div className="live-actions"><button className="secondary-btn compact" onClick={()=>adminApi.downloadStudent(detail.user.id)}>Export PDF</button><button className="ghost-btn compact" onClick={()=>{setSelected(null);setDetail(null);}}>Close</button></div></div><section className="stats-grid four"><StatCard label="Predicted" value={detail.progress?.[0]?.total_predicted_marks??"—"}/><StatCard label="Risk" value={detail.progress?.[0]?.risk_level||"—"}/><StatCard label="Adaptive test average" value={`${avg}%`} tone="blue"/><StatCard label="Tutor questions" value={detail.chats?.length||0} tone="purple"/></section><div className="junior-detail-columns"><div><h3>Recent predictions</h3>{(detail.progress||[]).slice(0,8).map(x=><div className="detail-line" key={x.id}><span>{x.createdAt?new Date(x.createdAt).toLocaleDateString():"—"}</span><strong>{x.total_predicted_marks??"—"} · {x.risk_level||"—"}</strong></div>)}</div><div><h3>Recent adaptive tests</h3>{(detail.tests||[]).slice(0,8).map(x=><div className="detail-line" key={x.id}><span>{x.test_type} · {x.difficulty}</span><strong>{x.score}/{x.total_marks}</strong></div>)}</div><div><h3>Recent tutor questions</h3>{(detail.chats||[]).slice(0,6).map(x=><div className="detail-line stacked" key={x.id}><span>{x.question}</span><small>{x.provider||"AI"}</small></div>)}</div></div></section>}
 </AppShell>;
}
export default function Page(){return <RequireAuth admin><LearningAdmin/></RequireAuth>;}
