"use client";

import { useEffect, useState } from "react";
import RequireAuth from "@/components/RequireAuth";
import AppShell from "@/components/AppShell";
import { aiApi, progressApi, testsApi } from "@/lib/api";

const subjects=[{name:"Mathematics",test_type:"Math"},{name:"Reading",test_type:"Reading"},{name:"Writing",test_type:"Writing"},{name:"Internal 1",test_type:"Internal 1"},{name:"Internal 2",test_type:"Internal 2"},{name:"Assignment",test_type:"Assignment"}];
function adaptive(p){if(!p)return null;if(String(p.risk_level).toLowerCase()==="low")return{name:"Advanced challenge",test_type:"Internal 2",difficulty:"Very Hard",context:"High performer; use application questions."};const scores={Math:Number(p.math_score||0),Reading:Number(p.reading_score||0),Writing:Number(p.writing_score||0)};const[weak,value]=Object.entries(scores).sort((a,b)=>a[1]-b[1])[0];if(value<65)return{name:`${weak} booster`,test_type:weak,difficulty:"Easy",context:`Focus on ${weak} fundamentals; latest score ${value}.`};return{name:"Balanced exam prep",test_type:"Internal 1",difficulty:"Medium",context:"Balanced conceptual and practical questions."};}
function TestCorner(){const[rec,setRec]=useState(null),[loading,setLoading]=useState(false),[questions,setQuestions]=useState([]),[answers,setAnswers]=useState({}),[current,setCurrent]=useState(0),[submitted,setSubmitted]=useState(false),[score,setScore]=useState(null),[meta,setMeta]=useState({}),[error,setError]=useState("");useEffect(()=>{progressApi.latest().then(x=>setRec(adaptive(x))).catch(()=>{});},[]);
 async function generate(subject,difficulty="Hard",context=""){setLoading(true);setError("");setQuestions([]);setAnswers({});setSubmitted(false);setScore(null);setCurrent(0);setMeta({test_type:subject.test_type,difficulty});try{const data=await aiApi.generateTest({difficulty,test_type:subject.test_type,learning_context:context});if(!data.questions?.length)throw new Error("No questions returned");setQuestions(data.questions);}catch(e){setError(e.message||"Could not generate assessment");}finally{setLoading(false);}}
 async function submit(){if(Object.keys(answers).length<questions.length){setError("Answer every question before submitting.");return;}let correct=0;const wrong=[];questions.forEach((q,i)=>{if(answers[i]===q.correct_answer)correct++;else wrong.push(q.question);});setScore(correct);setSubmitted(true);setCurrent(0);try{await testsApi.save({test_type:meta.test_type,difficulty:meta.difficulty,score:correct,total_marks:questions.length,wrong_answers:wrong});}catch(e){setError(e.message||"Could not save score");}}
 const q=questions[current];const resultPct=questions.length&&score!==null?Math.round(score/questions.length*100):null;
 if(q)return <AppShell title={meta.test_type||"Assessment"} subtitle={meta.difficulty||"Adaptive test"} actions={submitted?<span className={`pill ${resultPct>=75?"success":resultPct>=50?"warning":"danger"}`}>{score}/{questions.length} · {resultPct}%</span>:null}><section className="panel-card question-card-study"><div className="question-top-study"><button className="text-btn" onClick={()=>setQuestions([])}>Exit</button><span className="muted">Question {current+1} of {questions.length}</span></div><div className="question-progress-study"><span style={{width:`${((current+1)/questions.length)*100}%`}}/></div><h2>{q.question}</h2><div className="option-grid-study">{q.options.map(option=>{const selected=answers[current]===option;let cls=selected?"selected":"";if(submitted&&option===q.correct_answer)cls="correct";else if(submitted&&selected&&option!==q.correct_answer)cls="wrong";return <button key={option} disabled={submitted} className={`test-option-study ${cls}`} onClick={()=>setAnswers({...answers,[current]:option})}>{option}</button>;})}</div>{submitted&&answers[current]!==q.correct_answer&&<div className="success-note"><strong>Correct answer:</strong> {q.correct_answer}</div>}{error&&<div className="error-box">{error}</div>}<div className="question-actions-study"><button className="secondary-btn" disabled={current===0} onClick={()=>setCurrent(v=>v-1)}>Previous</button>{current<questions.length-1?<button className="primary-btn" onClick={()=>setCurrent(v=>v+1)}>Next</button>:!submitted?<button className="primary-btn" onClick={submit}>Submit</button>:<button className="primary-btn" onClick={()=>setQuestions([])}>New assessment</button>}</div></section></AppShell>;
 return <AppShell title="Adaptive Tests" subtitle="Junior assessments linked to the same student account">{rec&&<section className="hero-card adaptive-hero"><div><p className="eyebrow">Recommended from latest performance</p><h2>{rec.name}</h2><p className="muted">{rec.test_type} · {rec.difficulty}</p></div><button className="primary-btn" disabled={loading} onClick={()=>generate(rec,rec.difficulty,rec.context)}>Start adaptive test</button></section>}<section className="panel-card test-library-study"><div className="section-heading"><h2>Assessment library</h2></div>{loading?<div className="empty-state compact-empty"><strong>Generating questions…</strong></div>:<div className="assessment-grid-study">{subjects.map(s=><button key={s.test_type} className="assessment-card-study" onClick={()=>generate(s)}><strong>{s.name}</strong><span>Hard · 5 questions</span></button>)}</div>}{error&&<div className="error-box">{error}</div>}</section></AppShell>;
}
export default function Page(){return <RequireAuth><TestCorner/></RequireAuth>;}
