import { Router } from 'express';
import { requireAuth, requireAdmin } from '../middleware/auth.js';
import { User, StudentProgress, TestResult, ChatHistory, ActivityLog } from '../models/index.js';
import { plain, publicUser } from '../utils/serialize.js';
import { buildStudentReport } from './reports.js';
import { studentPdf, studentsPdf } from '../services/pdf.js';

const router=Router(); router.use(requireAuth,requireAdmin);
async function studentSummary(user){const [latest,tests,chats]=await Promise.all([StudentProgress.findOne({user_id:user._id}).sort({created_at:-1}).lean(),TestResult.find({user_id:user._id}).lean(),ChatHistory.countDocuments({user_id:user._id})]);const perc=tests.filter(x=>Number(x.total_marks)>0).map(x=>Number(x.score||0)/Number(x.total_marks)*100);return{...publicUser(user),latest_progress:latest?plain(latest,{keepUserId:false}):null,test_stats:{count:perc.length,average_score:perc.length?Number((perc.reduce((a,b)=>a+b,0)/perc.length).toFixed(1)):0,best_score:perc.length?Number(Math.max(...perc).toFixed(1)):0},chat_stats:{count:chats}};}
router.get('/overview',async(_req,res,next)=>{try{const since=new Date(Date.now()-24*3600*1000),onlineSince=new Date(Date.now()-5*60*1000);const [total,active,online,tests,chats,latestRows]=await Promise.all([User.countDocuments({role:'student',is_active:{$ne:false}}),User.countDocuments({role:'student',last_seen_at:{$gte:since}}),User.countDocuments({role:'student',last_seen_at:{$gte:onlineSince}}),TestResult.countDocuments({created_at:{$gte:since}}),ChatHistory.countDocuments({created_at:{$gte:since}}),StudentProgress.aggregate([{$sort:{created_at:-1}},{$group:{_id:'$user_id',row:{$first:'$$ROOT'}}}])]);res.json({total_users:total,active_24h:active,online_now:online,high_risk:latestRows.filter(x=>x.row?.risk_level==='High').length,tests_24h:tests,chats_24h:chats,generated_at:new Date()});}catch(e){next(e);}});
router.get('/users',async(req,res,next)=>{try{const search=String(req.query.search||'').trim(),page=Math.max(1,Number(req.query.page||1)),limit=Math.min(100,Math.max(1,Number(req.query.limit||20))),role=String(req.query.role||'student');const filter={role};if(search)filter.$or=[{email:{$regex:search,$options:'i'}},{'profile.name':{$regex:search,$options:'i'}}];const [users,total]=await Promise.all([User.find(filter).sort({'profile.name':1,email:1}).skip((page-1)*limit).limit(limit),User.countDocuments(filter)]);res.json({items:await Promise.all(users.map(studentSummary)),total,page,pages:Math.max(1,Math.ceil(total/limit))});}catch(e){next(e);}});
router.get('/users/:id',async(req,res,next)=>{try{const user=await User.findById(req.params.id);if(!user)return res.status(404).json({message:'Student not found'});const [progress,tests,chats,activity]=await Promise.all([StudentProgress.find({user_id:user._id}).sort({created_at:-1}).limit(200).lean(),TestResult.find({user_id:user._id}).sort({created_at:-1}).limit(200).lean(),ChatHistory.find({user_id:user._id}).sort({created_at:-1}).limit(100).lean(),ActivityLog.find({user_id:user._id}).sort({created_at:-1}).limit(200).lean()]);res.json({user:publicUser(user),progress:progress.map(x=>plain(x,{keepUserId:false})),tests:tests.map(x=>plain(x,{keepUserId:false})),chats:chats.map(x=>plain(x,{keepUserId:false})),activity:activity.map(x=>plain(x,{keepUserId:false}))});}catch(e){next(e);}});
router.get('/activity',async(req,res,next)=>{try{const limit=Math.min(200,Math.max(1,Number(req.query.limit||50)));const rows=await ActivityLog.find({}).sort({created_at:-1}).limit(limit).populate('user_id','email profile').lean();res.json(rows.map(row=>({id:String(row._id),action:row.action,page:row.page,metadata:row.metadata||{},createdAt:row.created_at,user:row.user_id?{id:String(row.user_id._id),email:row.user_id.email,name:row.user_id.profile?.name||''}:null})));}catch(e){next(e);}});
router.get('/report/students',async(_req,res,next)=>{try{const users=await User.find({role:'student'}).sort({created_at:-1}).limit(2000);const students=await Promise.all(users.map(studentSummary));const since=new Date(Date.now()-24*3600*1000),onlineSince=new Date(Date.now()-5*60*1000);const latestRows=await StudentProgress.aggregate([{$sort:{created_at:-1}},{$group:{_id:'$user_id',row:{$first:'$$ROOT'}}}]);const overview={total_users:students.length,active_24h:await User.countDocuments({role:'student',last_seen_at:{$gte:since}}),online_now:await User.countDocuments({role:'student',last_seen_at:{$gte:onlineSince}}),high_risk:latestRows.filter(x=>x.row?.risk_level==='High').length,tests_24h:await TestResult.countDocuments({created_at:{$gte:since}}),chats_24h:await ChatHistory.countDocuments({created_at:{$gte:since}})};res.json({overview,students,generated_at:new Date()});}catch(e){next(e);}});
router.get('/report/students.pdf',async(_req,res,next)=>{try{const users=await User.find({role:'student'});const rows=await Promise.all(users.map(studentSummary));const pdf=await studentsPdf(rows);res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition','attachment; filename="boardtrack-junior-students-report.pdf"');res.send(pdf);}catch(e){next(e);}});
router.get('/report/users/:id.pdf',async(req,res,next)=>{try{const user=await User.findById(req.params.id);if(!user)return res.status(404).json({message:'Student not found'});const data=await buildStudentReport(user);const pdf=await studentPdf(data);res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition','attachment; filename="student-learning-report.pdf"');res.send(pdf);}catch(e){next(e);}});
export default router;
