import { Router } from 'express';
import mongoose from 'mongoose';
import { requireAuth, requireAdmin } from '../middleware/auth.js';
import { User, ChapterProgress, SkillProgress, MockTest, StudyActivity, Vocabulary, AppConfig } from '../models/index.js';
import { plain, publicUser } from '../utils/serialize.js';
import { recordActivity } from '../services/activity.js';

const router = Router();
router.use(requireAuth);

const stages = {
  'first-cut': { label: 'First Cut', planned: 'firstCutPlanned', actual: 'firstCutActual', start: 'firstCutStartTime', end: 'firstCutEndTime', activityType: 'First Cut' },
  'revision-2': { label: 'Second Cut', planned: 'rev2Planned', actual: 'rev2Actual', start: 'rev2StartTime', end: 'rev2EndTime', activityType: 'Second Cut' },
  'revision-3': { label: 'Third Cut', planned: 'rev3Planned', actual: 'rev3Actual', start: 'rev3StartTime', end: 'rev3EndTime', activityType: 'Third Cut' },
};
const userId = req => String(req.query.userId || req.body.userId || req.params.userId || req.user._id);
const validId = id => mongoose.Types.ObjectId.isValid(id);
function canUse(req, id) { return req.user.role === 'admin' || String(req.user._id) === String(id); }
function todayKey() { return new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Kolkata', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date()); }
function statusFor(planned, actual) { if (actual) return 'COMPLETED'; if (planned && planned < todayKey()) return 'PENDING'; return 'NOT_STARTED'; }
const pretty = slug => String(slug || 'General').split('-').filter(Boolean).map(x => x[0].toUpperCase()+x.slice(1)).join(' ');
const deterministic = (uid, chapterId, stage) => `${uid}_${chapterId}_${stage}`;

async function syncStageActivities(uid, chapter, subjectSlug, values, removeMissing = true) {
  await Promise.all(Object.entries(stages).map(async ([key, stage]) => {
    const planned = String(values?.[stage.planned] || '').trim();
    const actual = String(values?.[stage.actual] || '').trim();
    const did = deterministic(uid, chapter.id, key);
    const existing = await StudyActivity.findOne({ userId: uid, deterministicId: did });
    if (!planned) {
      if (removeMissing && existing?.autoGenerated === true && existing?.assignedByAdmin !== true) await existing.deleteOne();
      return;
    }
    const base = {
      userId: uid, deterministicId: did, title: existing?.title || `${stage.label}: ${chapter.title || 'Chapter'}`,
      subject: pretty(subjectSlug), activityType: existing?.activityType || stage.activityType,
      scheduledDate: planned, startTime: String(values?.[stage.start] || ''), endTime: String(values?.[stage.end] || ''),
      status: actual ? 'COMPLETED' : existing?.status === 'COMPLETED' ? statusFor(planned, '') : (existing?.status || statusFor(planned, '')),
      notes: existing?.notes ?? `Automatically linked to ${stage.label} in chapter progress.`, autoGenerated: true, source: 'CHAPTER_PLAN',
      linkedChapterId: chapter.id, linkedChapterTitle: chapter.title || '', linkedSubjectSlug: subjectSlug || '', linkedStage: key,
      linkedPlannedField: stage.planned, linkedActualField: stage.actual, linkedActualDate: actual || '',
    };
    if (existing?.assignedByAdmin === true) {
      existing.status = base.status; existing.linkedActualDate = base.linkedActualDate; await existing.save();
    } else await StudyActivity.findOneAndUpdate({ userId: uid, deterministicId: did }, { $set: base }, { upsert: true, new: true, setDefaultsOnInsert: true });
  }));
}

router.get('/users', requireAdmin, async (_req, res, next) => { try { const rows = await User.find({}).sort({ 'profile.name': 1, email: 1 }); res.json(rows.map(publicUser)); } catch(e){next(e);} });
router.get('/users/:userId', async (req,res,next)=>{ try { if(!canUse(req,req.params.userId)) return res.status(403).json({message:'Access denied'}); const u=await User.findById(req.params.userId); res.json(u?publicUser(u):null);}catch(e){next(e);} });
router.patch('/users/:userId', async (req,res,next)=>{ try { if(!canUse(req,req.params.userId)) return res.status(403).json({message:'Access denied'}); const u=await User.findById(req.params.userId); if(!u)return res.status(404).json({message:'User not found'}); const p={...(u.profile?.toObject?.()||u.profile||{})}; for(const [k,v] of Object.entries(req.body||{})){ if(k==='name')p.name=String(v||''); else if(['grade','school','favorite_subject','dream_job','hobbies'].includes(k))p[k]=String(v||''); else if(req.user.role==='admin'&&k==='active')u.is_active=Boolean(v); } u.profile=p; await u.save(); res.json(publicUser(u)); }catch(e){next(e);} });

router.get('/chapter-progress', async (req,res,next)=>{try{const uid=userId(req);if(!canUse(req,uid))return res.status(403).json({message:'Access denied'});const rows=await ChapterProgress.find({userId:uid}).lean();res.json(rows.map(plain));}catch(e){next(e);}});
router.get('/chapter-progress/all', requireAdmin, async (_req,res,next)=>{try{const rows=await ChapterProgress.find({}).lean();res.json(rows.map(plain));}catch(e){next(e);}});
router.put('/chapter-progress/:chapterId', async (req,res,next)=>{try{const uid=userId(req);if(!canUse(req,uid))return res.status(403).json({message:'Access denied'});const chapter={id:req.params.chapterId,title:String(req.body.chapterTitle||req.body.chapter?.title||'Chapter')};const subjectSlug=String(req.body.subjectSlug||'');const values={...(req.body.values||req.body)};delete values.userId;delete values.chapter;delete values.values;const row=await ChapterProgress.findOneAndUpdate({userId:uid,chapterId:chapter.id},{$set:{userId:uid,chapterId:chapter.id,chapterTitle:chapter.title,subjectSlug,subjectName:pretty(subjectSlug),...values}},{upsert:true,new:true,setDefaultsOnInsert:true});await syncStageActivities(uid,chapter,subjectSlug,values,true);await recordActivity(req.user,'chapter_progress_updated','/subjects',{chapterId:chapter.id});res.json(plain(row));}catch(e){next(e);}});
router.post('/chapter-stage', async (req,res,next)=>{try{const uid=userId(req);if(!canUse(req,uid))return res.status(403).json({message:'Access denied'});const {chapterId,chapterTitle,subjectSlug,stageKey,values={}}=req.body;const stage=stages[stageKey];if(!stage)return res.status(400).json({message:'Invalid chapter stage'});const scheduledDate=String(values.scheduledDate||'').trim();if(!scheduledDate)return res.status(400).json({message:'Activity date is required'});const requested=['NOT_STARTED','IN_PROGRESS','COMPLETED','MISSED'].includes(values.status)?values.status:'NOT_STARTED';const existingActual=String(values.existingActualDate||'');const actual=requested==='COMPLETED'?scheduledDate:existingActual;const progressSet={userId:uid,chapterId,chapterTitle,subjectSlug,subjectName:pretty(subjectSlug),[stage.planned]:scheduledDate,[stage.start]:String(values.startTime||''),[stage.end]:String(values.endTime||'')};if(actual)progressSet[stage.actual]=actual;await ChapterProgress.findOneAndUpdate({userId:uid,chapterId},{$set:progressSet},{upsert:true});const did=deterministic(uid,chapterId,stageKey);const activity=await StudyActivity.findOneAndUpdate({userId:uid,deterministicId:did},{$set:{userId:uid,deterministicId:did,title:String(values.title||'').trim()||`${stage.label}: ${chapterTitle||'Chapter'}`,subject:pretty(subjectSlug),subjectSlug,chapterId,chapterTitle,activityType:stage.activityType,scheduledDate,startTime:String(values.startTime||''),endTime:String(values.endTime||''),status:actual?'COMPLETED':requested,notes:String(values.notes||''),autoGenerated:true,createdFromTimetable:true,source:'CHAPTER_PLAN',linkedChapterId:chapterId,linkedChapterTitle:chapterTitle||'',linkedSubjectSlug:subjectSlug||'',linkedStage:stageKey,linkedPlannedField:stage.planned,linkedActualField:stage.actual,linkedActualDate:actual}},{upsert:true,new:true});res.json(plain(activity));}catch(e){next(e);}});
router.post('/chapter-stage/assign', requireAdmin, async (req,res,next)=>{try{const uid=String(req.body.userId||'');const {chapterId,chapterTitle,subjectSlug,stageKey,values={}}=req.body;const stage=stages[stageKey];if(!stage)return res.status(400).json({message:'Invalid chapter stage'});const scheduledDate=String(values.scheduledDate||'').trim();if(!scheduledDate)return res.status(400).json({message:'Task date is required'});const existing=await ChapterProgress.findOne({userId:uid,chapterId}).lean();await ChapterProgress.findOneAndUpdate({userId:uid,chapterId},{$set:{userId:uid,chapterId,chapterTitle,subjectSlug,subjectName:pretty(subjectSlug),[stage.planned]:scheduledDate,[stage.start]:String(values.startTime||''),[stage.end]:String(values.endTime||'')}},{upsert:true});const actual=String(existing?.[stage.actual]||'');const did=deterministic(uid,chapterId,stageKey);const activity=await StudyActivity.findOneAndUpdate({userId:uid,deterministicId:did},{$set:{userId:uid,deterministicId:did,title:`${stage.label}: ${chapterTitle||'Chapter'}`,subject:pretty(subjectSlug),subjectSlug,chapterId,chapterTitle,activityType:stage.activityType,scheduledDate,startTime:String(values.startTime||''),endTime:String(values.endTime||''),status:statusFor(scheduledDate,actual),notes:String(values.notes||''),priority:String(values.priority||'NORMAL'),autoGenerated:true,source:'CHAPTER_PLAN',assignedByAdmin:true,assignedByUid:String(req.user._id),assignedByName:req.user.profile?.name||'Admin',linkedChapterId:chapterId,linkedChapterTitle:chapterTitle||'',linkedSubjectSlug:subjectSlug||'',linkedStage:stageKey,linkedPlannedField:stage.planned,linkedActualField:stage.actual,linkedActualDate:actual}},{upsert:true,new:true});res.json(plain(activity));}catch(e){next(e);}});
router.post('/chapter-progress/sync', async (req,res,next)=>{try{const uid=userId(req);if(!canUse(req,uid))return res.status(403).json({message:'Access denied'});const rows=await ChapterProgress.find({userId:uid}).lean();await Promise.all(rows.map(r=>syncStageActivities(uid,{id:r.chapterId,title:r.chapterTitle||'Chapter'},r.subjectSlug||r.subjectName||'General',r,false)));res.json({ok:true});}catch(e){next(e);}});

router.get('/skills', async (req,res,next)=>{try{const uid=userId(req);if(!canUse(req,uid))return res.status(403).json({message:'Access denied'});res.json((await SkillProgress.find({userId:uid}).lean()).map(plain));}catch(e){next(e);}});
router.put('/skills/:skillId', async (req,res,next)=>{try{const uid=userId(req);if(!canUse(req,uid))return res.status(403).json({message:'Access denied'});const row=await SkillProgress.findOneAndUpdate({userId:uid,skillId:req.params.skillId},{$set:{userId:uid,skillId:req.params.skillId,subject:req.body.subject||'',skillName:req.body.skillName||'',...(req.body.values||{})}},{upsert:true,new:true});res.json(plain(row));}catch(e){next(e);}});

router.get('/mock-tests', async (req,res,next)=>{try{const uid=userId(req);if(!canUse(req,uid))return res.status(403).json({message:'Access denied'});res.json((await MockTest.find({userId:uid}).sort({date:-1,createdAt:-1}).lean()).map(plain));}catch(e){next(e);}});
router.get('/mock-tests/all', requireAdmin, async (_req,res,next)=>{try{res.json((await MockTest.find({}).sort({date:-1,createdAt:-1}).lean()).map(plain));}catch(e){next(e);}});
router.post('/mock-tests', async (req,res,next)=>{try{const uid=userId(req);if(!canUse(req,uid))return res.status(403).json({message:'Access denied'});const row=await MockTest.create({userId:uid,...req.body.values});await recordActivity(req.user,'mock_test_added','/mock-tests',{userId:uid});res.status(201).json(plain(row));}catch(e){next(e);}});
router.delete('/mock-tests/:id', async (req,res,next)=>{try{const row=await MockTest.findById(req.params.id);if(!row)return res.status(204).end();if(!canUse(req,row.userId))return res.status(403).json({message:'Access denied'});await row.deleteOne();res.json({ok:true});}catch(e){next(e);}});

router.get('/settings', async (_req,res,next)=>{try{const row=await AppConfig.findOne({key:'performance'}).lean();res.json(row?plain(row):null);}catch(e){next(e);}});
router.put('/settings', requireAdmin, async (req,res,next)=>{try{const row=await AppConfig.findOneAndUpdate({key:'performance'},{$set:{key:'performance',...req.body}},{upsert:true,new:true});res.json(plain(row));}catch(e){next(e);}});

router.get('/activities', async (req,res,next)=>{try{const uid=userId(req);if(!canUse(req,uid))return res.status(403).json({message:'Access denied'});res.json((await StudyActivity.find({userId:uid}).sort({scheduledDate:1,startTime:1}).lean()).map(plain));}catch(e){next(e);}});
router.get('/activities/all', requireAdmin, async (_req,res,next)=>{try{res.json((await StudyActivity.find({}).sort({scheduledDate:1,startTime:1}).lean()).map(plain));}catch(e){next(e);}});
router.post('/activities', async (req,res,next)=>{try{const uid=userId(req);if(!canUse(req,uid))return res.status(403).json({message:'Access denied'});const row=await StudyActivity.create({userId:uid,status:'NOT_STARTED',...(req.body.values||{})});res.status(201).json(plain(row));}catch(e){next(e);}});
router.patch('/activities/:id', async (req,res,next)=>{try{const row=await StudyActivity.findById(req.params.id);if(!row)return res.status(404).json({message:'Activity not found'});if(!canUse(req,row.userId))return res.status(403).json({message:'Access denied'});Object.assign(row,req.body.values||{});await row.save();res.json(plain(row));}catch(e){next(e);}});
router.patch('/activities/:id/status', async (req,res,next)=>{try{const row=await StudyActivity.findById(req.params.id);if(!row)return res.status(404).json({message:'Activity not found'});if(!canUse(req,row.userId))return res.status(403).json({message:'Access denied'});const status=String(req.body.status||'NOT_STARTED');row.status=status;if(row.autoGenerated===true&&row.source==='CHAPTER_PLAN'&&row.linkedChapterId&&row.linkedActualField){const actual=status==='COMPLETED'?todayKey():'';await ChapterProgress.updateOne({userId:row.userId,chapterId:row.linkedChapterId},{$set:{[row.linkedActualField]:actual}});row.linkedActualDate=actual;}await row.save();res.json(plain(row));}catch(e){next(e);}});
router.delete('/activities/:id', async (req,res,next)=>{try{const row=await StudyActivity.findById(req.params.id);if(!row)return res.status(204).end();if(!canUse(req,row.userId))return res.status(403).json({message:'Access denied'});if(row.autoGenerated===true&&row.source==='CHAPTER_PLAN')return res.status(409).json({message:'Chapter plan activities must be removed from Subjects'});await row.deleteOne();res.json({ok:true});}catch(e){next(e);}});

router.get('/vocabulary', async (req,res,next)=>{try{const uid=userId(req);if(!canUse(req,uid))return res.status(403).json({message:'Access denied'});res.json((await Vocabulary.find({userId:uid}).sort({learnedOn:-1,word:1}).lean()).map(plain));}catch(e){next(e);}});
router.post('/vocabulary', async (req,res,next)=>{try{const uid=userId(req);if(!canUse(req,uid))return res.status(403).json({message:'Access denied'});const row=await Vocabulary.create({userId:uid,...(req.body.values||{})});res.status(201).json(plain(row));}catch(e){next(e);}});
router.patch('/vocabulary/:id', async (req,res,next)=>{try{const row=await Vocabulary.findById(req.params.id);if(!row)return res.status(404).json({message:'Word not found'});if(!canUse(req,row.userId))return res.status(403).json({message:'Access denied'});Object.assign(row,req.body.values||{});await row.save();res.json(plain(row));}catch(e){next(e);}});
router.delete('/vocabulary/:id', async (req,res,next)=>{try{const row=await Vocabulary.findById(req.params.id);if(!row)return res.status(204).end();if(!canUse(req,row.userId))return res.status(403).json({message:'Access denied'});await row.deleteOne();res.json({ok:true});}catch(e){next(e);}});

export default router;
